language: node_js

node_js:
- "node"

cache:
  directories:
  - node_modules

install:
- npm install --progress=false
- npm run build

script:
- npm run test-travis

# after_success: 
# - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
- provider: script
  skip_cleanup: true
  script: bin/togemfury.sh
